- name: how to traverse through a loop
  hosts: jumpserver
  vars: 
  tasks:
    - name: Loops
      loop:
        - ball
        - bat
        - gloves
      ansible.builtin.debug:
        msg: I have - {{item}}
  tasks:
    - name: Loops
      loop:
        - { name: ball, quantity: 6 }
        - { name: bat, quantity: 1 }
        - { name: gloves, quantity: 2 }
      ansible.builtin.debug:
        msg: I have - {{item.quantity}} {{item.name}} (s)
