- name: Variable demo
  hosts: jumpserver
  vars:
    URL: some value for variable 
  tasks:
  - name: To print values of a variable
    ansible.builtin.debug:
      msg: Hello - {{URL}}

- name: Variable demo - using file
  hosts: jumpserver
  vars_files:
    - File_containing_variable_value.yml
  tasks:
    - name: To retreive variable value from file
      ansible.builtin.debug:
      msg: Hello - {{URL}}
