- name: Variable demo
  hosts: jumpserver
  vars:
    URL: some value for variable 
  tasks:
  - name: To print values of a variable
    ansible.builtin.debug:
      msg: Hello - {{URL}}

- name: Variable demo - using file
  hosts: jumpserver
  vars_files:
    - File_Containing_variable_value.yml
  tasks:
  - name: To retreive variable value from file
    ansible.builtin.debug:
      msg: Hello - {{URL}}


- name: Varibale demo - variables under tasks
  hosts: jumpserver
  tasks:
  - name: Print message
    vars: 
      URL: abc
    ansible.builtin.debug:
      msg: Hello - {{URL}}

- name: Demo on facts/pre-defined variables
  hosts: jumpserver
  tasks:
  - name: Print message
    ansible.builtin.debug:
      msg: My name is - {{ansible_hostname}}
  - name: Print message2
    ansible.builtin.debug:      
      msg: My IP is - {{ansible_all_ipv4_addresses}}  
